log_level: info

behavior:
  read_only: true
  auto_gc_behavior:
    enable: true
    archive_level: 1

system_variables:
  dolt_stats_enabled: 0

listener:
  host: 127.0.0.1
  port: 3306
  max_connections: 100
  read_timeout_millis: 600000
  write_timeout_millis: 600000
